Repository seapagan/fastapi-template, pull requests merged in 2023-06, with the labels that each got.

#92 Continue to improve test coverage
  README.md
  config/helpers.py
  managers/auth.py
  managers/user.py
  pyproject.toml
  tests/conftest.py
  tests/helpers.py
  tests/integration/test_auth_routes.py
  tests/integration/test_home_routes.py
  tests/unit/test_auth_manager.py
  tests/unit/test_auth_manager_bearer_class.py
  tests/unit/test_auth_manager_helpers.py
  tests/unit/test_config_helpers.py
  tests/unit/test_database_db.py
  tests/unit/test_email_manager.py
  tests/unit/test_user_manager.py
Labels: tests

#96 Minimal tidying of documentation
  README.md
  docs/contributing.md
  docs/usage/add-user.md
  docs/usage/configuration/database.md
  docs/usage/configuration/dot-env.md
  docs/usage/configuration/setup.md
  docs/usage/dev-server.md
  docs/usage/installation.md
Labels: documentation

#103 Add development information to Docs website
  docs/contributing.md
  docs/usage/dev/docker.md
  docs/usage/dev/documentation.md
  docs/usage/dev/local.md
  mkdocs.yml
Labels: documentation

#101 Docker Support
  .env.example
  Dockerfile
  README.md
  docker-compose.yml
  docs/development/docker.md
  requirements.txt
Labels: enhancement

#120 add custom domain for docs
  README.md
  docs/CNAME
  mkdocs.yml
Labels: documentation

#126 Refactor versioning
  README.md
  docs/contributing.md
  docs/index.md
  pyproject.toml
Labels: documentation, Refactor

#130 Add release version to docs
  docs/index.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#131 Migrate startup to lifespan
  app/main.py
  pyproject.toml
Labels: Refactor
